#pragma config(Motor,  port1,           BLOCKED,       tmotorNone, openLoop)
#pragma config(Motor,  port2,           RightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           LeftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           ShooterMotor,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           MannequinServo, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while (true) {

	}

}
