#pragma config(Motor,  port2,           RightMotor,    tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port3,           LeftMotor,     tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port4,           CanMotor,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	bool forward = true;
	while(true) {
		if(vexRT[Btn6U]){
			// Pull in paint cans
			motor[CanMotor] = 127;
		}
		else if(vexRT[Btn6D]){
			// Push cans back out
			motor[CanMotor] = -127;
		}
		else {
			motor[CanMotor] = 0;
		}

		if(vexRT[Btn5U]){
			forward = true;
		}
		else if (vexRT[Btn5D]){
			forward = false;
		}

		//control tank drive
		if(forward){
			motor[RightMotor] = vexRT[Ch2];
			motor[LeftMotor] = vexRT[Ch3];
		}
		else {
			motor[RightMotor] = -1 * vexRT[Ch3];
			motor[LeftMotor] = -1 * vexRT[Ch2];
		}
	}
}
