#pragma config(Motor,  port2,           RightMotor,    tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port3,           LeftMotor,     tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port4,           CanMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           MannequinServoLeft, tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           MannequinServoRight, tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           ShooterMotor,  tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Btn6U = pull in paint cans
Btn6D = push out paint cans
Btn7U = toggle to backward drive (default = forward)
Btn5U = toggle to arm up (default = arm down)
Btn8U = hold to fire the shooter
Ch2 & Ch3 (joystick) = right & left motor forward/backward
*/

task main() {
	// boolean variable to control the tank drive state
	bool forward = true;

	// boolean variable to control the arm state
	bool armUp = true;

	while (true) {

		// controls the paint can apparatus
		if (vexRT[Btn6U]){
			motor[CanMotor] = 127; // pull in paint cans
		}
		else if (vexRT[Btn6D]){
			motor[CanMotor] = -127; // push cans back out
		}
		else {
			motor[CanMotor] = 0; // sets motor to neutral state
		}

		// controls the shooter
		if (vexRT[Btn8U]){
		  motor[ShooterMotor] = 127; // start the shooter motor
		}
		else {
		  motor[ShooterMotor] = 0; // stop the shooter when the button isn't held
		}

		// sets tank drive state
		if (vexRT[Btn7U]) {
			forward = false; // backward state
		}
		else {
			forward = true; // forward state
		}

		// control tank drive
		if (forward) {
			// drive forward with full power on both motors
			motor[RightMotor] = vexRT[Ch2];
			motor[LeftMotor] = vexRT[Ch3];
		}
		else {
			// drive reverse with full power on both motors;
			motor[RightMotor] = -1 * vexRT[Ch3];
			motor[LeftMotor] = -1 * vexRT[Ch2];
		}

		// mannequin arm controls
		// non-inverted controls: U -> raises the arm
		// 										    D -> lowers the arm


		/*if (vexRT[Btn5U]) {
			// set both servos to full power forward
			motor[MannequinServoRight] = 127;
			motor[MannequinServoLeft] = 127;
		}
		else if (vexRT[Btn5D]) {
			// set both servos to full power reverse
			motor[MannequinServoRight] = -127;
			motor[MannequinServoLeft] = -127;
		}
		else {
			// set both servos to neutral
			// default state is full up
			motor[MannequinServoRight] = 127;
			motor[MannequinServoLeft] = 127;
		}*/

		if (vexRT[Btn5U]) {
			armUp = true;
		}
		else {
			armUp = false;
		}
	}
}
